import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { Button, Pane, Text } from "evergreen-ui";
import { useRouter } from "next/router";
import { Routes } from "@/routes/routes";
import { useEffect, useState } from "react";
import styled from "styled-components";

const inter = Inter({subsets: ['latin']})

export default function Home() {

    const router = useRouter();

    const localScore = typeof window !== 'undefined' ? JSON.parse(localStorage.getItem("score") || '[]') : null
    const [score, setScore] = useState<Array<string>>()

    useEffect(() => {
        localScore && setScore(localScore)
    }, localScore)

    return (
        <>
            <Head>
                <title>Quiz App</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main className={`${styles.main} ${inter.className}`}>
                {score?.length &&
                    <ScoreWrapper>
                        <Text color="white" fontSize="18px">Score</Text>
                        {score.map((score: string) => {
                            return (
                                <>
                                    <Divider/>
                                    <StyledScore>{score}</StyledScore>
                                </>
                            )
                        })}
                    </ScoreWrapper>
                }
                <Button fontSize="18px" onClick={() => router.push(`${Routes.START_QUIZ}`)}>Start quiz</Button>
            </main>
        </>
    )
}

const ScoreWrapper = styled(Pane)`
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  gap: 8px;
  border: 2px solid lightgoldenrodyellow;
  border-radius: 10px;
  width: 400px;
  padding: 10px;
`;

const StyledScore = styled(Pane)`
  display: flex;
  align-items: center;
  justify-content: center;
  width: 100%;
  margin: 2px;
  padding: 5px;
`;

const Divider = styled(Pane)`
  width: 100%;
  height: 1px;
  background-color: lightgoldenrodyellow;
`
